enableGlobalCache: true

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

unsafeHttpWhitelist:
  - localhost

yarnPath: .yarn/releases/yarn-berry.js
