[build.environment]
  NODE_VERSION = "18"
[build]
  publish = "docs/.vitepress/dist"
  command = "pnpm run build:common && pnpm run build:scripts && pnpm run build && pnpm run build:meta && pnpm run build:docs"
