import '@/components/preset/css'
import '@/components/avatar/css'
import '@/components/dropdown/css'
import '@/components/linker/css'
import '@/components/menu/css'
import '@/components/native-scroll/css'
import '@/components/switch/css'
import '@/css/layout.css'
