name: Bug report

description: Report a bug about Vexip UI

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: I am doing ... What I expect is ... What actually happening is ...
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Reproduction
      description: Please provide a link that can reproduce the problem you ran init. You can use [playground](https://playground.vexipui.com/) or use `npm create vexip` as a starter template.
      placeholder: Reproduction URL
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any reproduction steps that may need to be described.
      placeholder: Run `npm install` followed by `npm run dev`

  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `npx envinfo --system --npmPackages '{vexip-ui,@vexip-ui/*}' --binaries --browsers`
      render: shell
      placeholder: System, Binaries, Browsers

  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](https://github.com/vexip-ui/vexip-ui/blob/main/CONTRIBUTING.md).
          required: true
        - label: Read the [docs](https://www.vexipui.com/).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/vexip-ui/vexip-ui/issues) that reports the same bug to avoid creating a duplicate.
          required: true
        - label: Make sure this is a Vexip UI issue.
          required: true
        - label: The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
          required: true
