import _Vue from 'vue';
import Alert from '../components/alert';
import Anchor from '../components/anchor';
import AnchorLink from '../components/anchor/anchor-link.vue';
import AutoComplete from '../components/auto-complete';
import Badge from '../components/badge';
import Breadcrumb from '../components/breadcrumb';
import BreadcrumbItem from '../components/breadcrumb/breadcrumb-item.vue';
import Bubble from '../components/bubble';
import Button from '../components/button';
import ButtonGroup from '../components/button/button-group.vue';
import Calendar from '../components/calendar';
import Card from '../components/card';
import Carousel from '../components/carousel';
import CarouselItem from '../components/carousel-item';
import Checkbox from '../components/checkbox';
import CheckboxGroup from '../components/checkbox/checkbox-group.vue';
import Collapse from '../components/collapse';
import CollapsePane from '../components/collapse/collapse-pane.vue';
import CollapseTransition from '../components/collapse/collapse-transition.js';
import ColorPicker from '../components/color-picker';
import DatePicker from '../components/date-picker';
import Divider from '../components/divider';
import Drawer from '../components/drawer';
import Dropdown from '../components/dropdown';
import DropdownList from '../components/dropdown/dropdown-list.vue';
import DropdownItem from '../components/dropdown/dropdown-item.vue';
import Form from '../components/form';
import FormItem from '../components/form/form-item.vue';
import Icon from '../components/icon';
import Input from '../components/input';
import Linker from '../components/linker';
import Masker from '../components/masker';
import Menu from '../components/menu';
import MenuGroup from '../components/menu/menu-group.vue';
import MenuItem from '../components/menu/menu-item.vue';
import Modal from '../components/modal';
import MultipleInput from '../components/multiple-input';
import NumberInput from '../components/number-input';
import Option from '../components/option';
import OptionGroup from '../components/option/option-group.vue';
import Pagination from '../components/pagination';
import Picture from '../components/picture';
import PictureViewer from '../components/picture/picture-viewer.vue';
import Popup from '../components/popup';
import Progress from '../components/progress';
import Radio from '../components/radio';
import RadioGroup from '../components/radio/radio-group.vue';
import Scroll from '../components/scroll';
import Select from '../components/select';
import Slider from '../components/slider';
import Split from '../components/split';
import Stack from '../components/stack';
import StackItem from '../components/stack-item';
import Switcher from '../components/switcher';
import Table from '../components/table';
import TableColumn from '../components/table/table-column.vue';
import TabNav from '../components/tabs/tab-nav.vue';
import TabNavItem from '../components/tabs/tab-nav-item.vue';
import Tabs from '../components/tabs';
import TabPane from '../components/tab-pane';
import Tag from '../components/tag';
import Textarea from '../components/textarea';
import TimePicker from '../components/date-picker/time-picker.vue';
import Timeline from '../components/timeline';
import TimelineItem from '../components/timeline/timeline-item.vue';
import Tooltip from '../components/tooltip';
import Tree from '../components/tree';
import Upload from '../components/upload';
import Wheel from '../components/wheel';
import WheelItem from '../components/wheel/wheel-item.vue';
import Confirm from '../components/confirm';
import Message from '../components/message';
import Notice from '../components/notice';
import Row from '../components/row';
import Column from '../components/row/column.vue';
import '../icons';
import './style/index.scss';
export interface InstallOptions {
    prefix?: string;
    config?: {
        [x: string]: any;
    };
}
export { Confirm, Message, Notice, Column, Row, Alert, Anchor, AnchorLink, AutoComplete, Badge, Breadcrumb, BreadcrumbItem, Bubble, Button, ButtonGroup, Calendar, Card, Carousel, CarouselItem, Checkbox, CheckboxGroup, Collapse, CollapsePane, CollapseTransition, ColorPicker, DatePicker, Divider, Drawer, Dropdown, DropdownList, DropdownItem, Form, FormItem, Icon, Input, Linker, Masker, Menu, MenuGroup, MenuItem, Modal, MultipleInput, NumberInput, Option, OptionGroup, Pagination, Picture, PictureViewer, Popup, Progress, Radio, RadioGroup, Scroll, Select, Slider, Split, Stack, StackItem, Switcher, Table, TableColumn, TabNav, TabNavItem, Tabs, TabPane, Tag, Textarea, TimePicker, Timeline, TimelineItem, Tooltip, Tree, Upload, Wheel, WheelItem };
declare const _default: {
    Column: import("vue").VueConstructor<_Vue>;
    Row: import("vue").VueConstructor<_Vue>;
    Alert: import("vue").VueConstructor<_Vue>;
    Anchor: import("vue").VueConstructor<_Vue>;
    AnchorLink: import("vue").VueConstructor<_Vue>;
    AutoComplete: import("vue").VueConstructor<_Vue>;
    Badge: import("vue").VueConstructor<_Vue>;
    Breadcrumb: import("vue").VueConstructor<_Vue>;
    BreadcrumbItem: import("vue").VueConstructor<_Vue>;
    Bubble: import("vue").VueConstructor<_Vue>;
    Button: import("vue").VueConstructor<_Vue>;
    ButtonGroup: import("vue").VueConstructor<_Vue>;
    Calendar: import("vue").VueConstructor<_Vue>;
    Card: import("vue").VueConstructor<_Vue>;
    Carousel: import("vue").VueConstructor<_Vue>;
    CarouselItem: import("vue").VueConstructor<_Vue>;
    Checkbox: import("vue").VueConstructor<_Vue>;
    CheckboxGroup: import("vue").VueConstructor<_Vue>;
    Collapse: import("vue").VueConstructor<_Vue>;
    CollapsePane: import("vue").VueConstructor<_Vue>;
    CollapseTransition: any;
    ColorPicker: import("vue").VueConstructor<_Vue>;
    DatePicker: import("vue").VueConstructor<_Vue>;
    Divider: import("vue").VueConstructor<_Vue>;
    Drawer: import("vue").VueConstructor<_Vue>;
    Dropdown: import("vue").VueConstructor<_Vue>;
    DropdownList: import("vue").VueConstructor<_Vue>;
    DropdownItem: import("vue").VueConstructor<_Vue>;
    Form: import("vue").VueConstructor<_Vue>;
    FormItem: import("vue").VueConstructor<_Vue>;
    Icon: any;
    Input: import("vue").VueConstructor<_Vue>;
    Linker: import("vue").VueConstructor<_Vue>;
    Masker: import("vue").VueConstructor<_Vue>;
    Menu: import("vue").VueConstructor<_Vue>;
    MenuGroup: import("vue").VueConstructor<_Vue>;
    MenuItem: import("vue").VueConstructor<_Vue>;
    Modal: import("vue").VueConstructor<_Vue>;
    MultipleInput: import("vue").VueConstructor<_Vue>;
    NumberInput: import("vue").VueConstructor<_Vue>;
    Option: import("vue").VueConstructor<_Vue>;
    OptionGroup: import("vue").VueConstructor<_Vue>;
    Pagination: import("vue").VueConstructor<_Vue>;
    Picture: import("vue").VueConstructor<_Vue>;
    PictureViewer: import("vue").VueConstructor<_Vue>;
    Popup: import("vue").VueConstructor<_Vue>;
    Progress: import("vue").VueConstructor<_Vue>;
    Radio: import("vue").VueConstructor<_Vue>;
    RadioGroup: import("vue").VueConstructor<_Vue>;
    Scroll: import("vue").VueConstructor<_Vue>;
    Select: import("vue").VueConstructor<_Vue>;
    Slider: import("vue").VueConstructor<_Vue>;
    Split: import("vue").VueConstructor<_Vue>;
    Stack: import("vue").VueConstructor<_Vue>;
    StackItem: import("vue").VueConstructor<_Vue>;
    Switcher: import("vue").VueConstructor<_Vue>;
    Table: import("vue").VueConstructor<_Vue>;
    TableColumn: import("vue").VueConstructor<_Vue>;
    TabNav: import("vue").VueConstructor<_Vue>;
    TabNavItem: import("vue").VueConstructor<_Vue>;
    Tabs: import("vue").VueConstructor<_Vue>;
    TabPane: import("vue").VueConstructor<_Vue>;
    Tag: import("vue").VueConstructor<_Vue>;
    Textarea: import("vue").VueConstructor<_Vue>;
    TimePicker: import("vue").VueConstructor<_Vue>;
    Timeline: import("vue").VueConstructor<_Vue>;
    TimelineItem: import("vue").VueConstructor<_Vue>;
    Tooltip: import("vue").VueConstructor<_Vue>;
    Tree: import("vue").VueConstructor<_Vue>;
    Upload: import("vue").VueConstructor<_Vue>;
    Wheel: import("vue").VueConstructor<_Vue>;
    WheelItem: import("vue").VueConstructor<_Vue>;
    install: (Vue: import("vue").VueConstructor<_Vue>, options?: InstallOptions) => void;
    version: any;
    Confirm: import("../components/confirm").ConfirmManager;
    Message: import("../components/message").MessageManager;
    Notice: import("../components/notice").NoticeManager;
};
export default _default;
