#!/usr/bin/env bash
changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"

check_run() {
	if (echo "$changed_files" | grep --quiet "$1"); then
    echo "Detected a change in pnpm-lock.yaml and started updating dependencies"
    eval "$2"
  fi
}

check_run pnpm-lock.yaml "pnpm install"
